---
- hosts: admin
  tasks:

    - name: setup private key
      copy: src=~/.vagrant.d/insecure_private_key dest=/home/vagrant/.ssh/id_rsa            mode=0600

    - name: create ssh config
      file: path=/home/vagrant/.ssh/config state=touch

    - name: disable strict host checking
      lineinfile: dest=/home/vagrant/.ssh/config regexp='StrictHost' line="StricthostKeyChecking no"

    - name: Cluster directory
      file: name=/home/vagrant/cluster state=directory owner=vagrant

    - name: create the new cluster
      command: /usr/bin/ceph-deploy new ceph1 chdir=/home/vagrant/cluster 
                creates=/home/ceph/cluster/ceph.conf

    - name: tweak osd pool size
      lineinfile: dest=/home/vagrant/cluster/ceph.conf regexp=osd line="osd pool default size = 2"

    - name: install ceph
      command: /usr/bin/ceph-deploy install admin ceph1 ceph2 ceph3 chdir=/home/vagrant/cluster

    - name: create initial monitors
      command: /usr/bin/ceph-deploy mon create-initial chdir=/home/vagrant/cluster

    - name: prepare osd sdb
      command: /usr/bin/ceph-deploy osd prepare {{ item }}:/dev/sdb chdir=/home/vagrant/cluster
      with_items:
        - ceph1
        - ceph2
        - ceph3

    - name: prepare osd sdc
      command: /usr/bin/ceph-deploy osd prepare {{ item }}:/dev/sdc chdir=/home/vagrant/cluster
      with_items:
        - ceph1
        - ceph2
        - ceph3

    - name: activeate osd sdb
      command: /usr/bin/ceph-deploy osd activate {{ item }}:/dev/sdb1:/dev/sdb2 chdir=/home/vagrant/cluster
      with_items:
        - ceph1
        - ceph2
        - ceph3

    - name: activeate osd sdc
      command: /usr/bin/ceph-deploy osd activate {{ item }}:/dev/sdc1:/dev/sdc2 chdir=/home/vagrant/cluster
      with_items:
        - ceph1
        - ceph2
        - ceph3

    - name: Deploy config and keyrings
      command: /usr/bin/ceph-deploy admin admin ceph1 ceph2 ceph3 chdir=/home/vagrant/cluster
