---
- hosts: all
  tasks:
    - name: upgrade packages
      apt: upgrade=dist update_cache=yes dpkg_options='force-confold,force-confdef'

    - name: Add ceph key
      apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present

    - name: Add ceph repo
      apt_repository: repo='deb http://ceph.com/debian-firefly/ precise main' state=present

    - name: create ceph user
      user: name=ceph shell=/bash/bash group=admin

    - name: setup ssh dir
      file: /home/ceph/.ssh state=directory mode=0700 owner=ceph group=ceph

    - name: add keys
      copy: src=files/ceph_key dest=/home/ceph/.ssh/id_rsa owner=ceph group=ceph mode=0600

    - name: setup ssh access
      authorized_key: user=ceph key="{{ item }}"
      with_file:
        - files/ceph_key.pub

    - name: setup hosts file
      lineinfile: dest=/etc/hosts regexp='admin' line="172.24.0.5 admin"
      lineinfile: dest=/etc/hosts regexp='ceph1' line="172.24.0.1 ceph1"
      lineinfile: dest=/etc/hosts regexp='ceph2' line="172.24.0.2 ceph2"
      lineinfile: dest=/etc/hosts regexp='ceph3' line="172.24.0.3 ceph3"
      lineinfile: dest=/etc/hosts regexp='ceph4' line="172.24.0.4 ceph4"

- hosts: admin
  tasks:
    - name: Add ceph-deploy
      apt: name=ceph-deploy state=present update_cache=yes

